name: flag
description: A flag Flutter package. Use for showing flags. Thanks for https://github.com/madebybowtie/FlagKit And https://github.com/hjnilsson/country-flags Projects.
version: 1.0.2
homepage: https://github.com/LunaGao/flag_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/svg2/
    - res/svg1/
